version: '3'

services:
  mybackend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:8080'
    volumes:
      - ./src:/myfolder/src
    env_file:
      - ./.env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    container_name: mytodoapp_container
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'mytodoapp'
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql/:/var/lib/mysql
